# Generated by Django 3.2.10 on 2021-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('p_id', models.CharField(max_length=10)),
                ('authors', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=300)),
            ],
        ),
    ]
