# Generated by Django 3.2.10 on 2021-12-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rol',
            new_name='papers',
        ),
    ]
