# Generated by Django 3.2.10 on 2021-12-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_rol_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(upload_to='~/Desktop/Papers'),
        ),
    ]
