# Generated by Django 3.2.10 on 2022-02-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_papers_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
