# Generated by Django 3.2.10 on 2022-02-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_papers_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='authors',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='papers',
            name='category',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='papers',
            name='keywords',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='papers',
            name='p_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='papers',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
